app:
  name: ChatApp
  version: 1.0.0
  timezone: UTC
server:
  read_timout: 5s
  write_timeout: 5s
database:
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 5m
jwt: 
  acess_ttl: 30m
  refresh_ttl: 168h
  issuer: ChatAppIssuer